---
- name: Setup servers
  hosts: all
  become: yes

  tasks:
    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - mysql-server
        - apache2

    - name: Start and enable apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Start and enable Mysql-Server
      service:
        name: mysql
        state: started
        enable: yes

    - name: Show environment info
      debug:
        msg: "This host is in {{ env }} environment"
