---
- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_version|lower }}.yml"
    - "{{ ansible_distribution|lower }}.yml"
    - "default.yml"

- name: Install Apache and PHP packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ apache_php_packages }}"

- name: Ensure Apache is running and enabled
  service:
    name: "{{ apache_service_name }}"
    state: started
    enabled: yes

- name: Download WordPress
  get_url:
    url: "https://wordpress.org/latest.tar.gz"
    dest: "/tmp/wordpress.tar.gz"

- name: Extract WordPress
  unarchive:
    src: "/tmp/wordpress.tar.gz"
    dest: "{{ wordpress_install_dir }}"
    remote_src: yes

- name: Configure WordPress
  template:
    src: wp-config.php.j2
    dest: "{{ wordpress_install_dir }}/wordpress/wp-config.php"
