---
- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_version|lower }}.yml"
    - "{{ ansible_distribution|lower }}.yml"
    - "default.yml"

- name: Install MySQL packages
  package:
    name: "{{ mysql_packages }}"
    state: present

- name: Ensure MySQL service is running and enabled
  service:
    name: "{{ mysql_service_name }}"
    state: started
    enabled: yes

- name: Secure MySQL installation
  command: mysql_secure_installation
  when: mysql_secure_installation | default(true)
  args:
    stdin: "{{ mysql_root_password }}"

- name: Create WordPress database
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create WordPress database user
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
