{
 "title": "Backup Status & Metrics",
 "tags": [ "backup" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Success backups",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(server_backup_success) + sum(service_backup_success)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed backups",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(server_backup_success == 0) OR vector(0)) + \r\n(count(service_backup_success == 0) OR vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Services Backup ",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "service_backup_timestamp * 1000",
     "legendFormat": "__auto"
    },
    { "expr": "service_backup_size_bytes", "legendFormat": "__auto" },
    { "expr": "service_backup_success", "legendFormat": "__auto" },
    { "expr": "service_db_size_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Services Backup Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "service_backup_size_bytes", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Services DB Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "service_db_size_bytes", "legendFormat": "{{service}}" }
   ]
  },
  { "title": "Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Servers Backup ",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    { "expr": "server_backup_timestamp * 1000", "legendFormat": "__auto" },
    { "expr": "server_backup_size_bytes", "legendFormat": "__auto" },
    { "expr": "server_backup_success", "legendFormat": "__auto" },
    { "expr": "server_db_size_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Servers Backup Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "server_backup_size_bytes", "legendFormat": "{{server}}" }
   ]
  },
  {
   "title": "Servers DB Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "server_db_size_bytes", "legendFormat": "{{server}}" }
   ]
  }
 ]
}