# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  # Client VM конфиг
  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/focal64"
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.56.13"
    web.vm.boot_timeout = 600
    
    web.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y apache2 nginx
    SHELL
  end
end