# Dockerfile.debian
FROM debian:12

RUN apt-get update && \
    apt-get install -y nginx && \
    mkdir -p /opt/www

COPY index.html /opt/www/
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
