# Dockerfile.alpine
FROM alpine:latest

RUN apk add --no-cache nginx && \
    mkdir -p /opt/www && \
    mkdir -p /run/nginx

COPY index.html /opt/www/
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
