---
stages:
  - lint
  - test
  - plan
  - apply
  - configure
  - adhoc
  - backup
  - destroy

# workflow:
#   rules:
#     - if: $CI_MERGE_REQUEST_ID
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
