apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wordpress.fullname" . }}-wordpress
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
data:
  WORDPRESS_DB_HOST: {{ .Values.wordpress.env.WORDPRESS_DB_HOST | quote }}
  WORDPRESS_DB_NAME: {{ .Values.wordpress.env.WORDPRESS_DB_NAME | quote }}
  WORDPRESS_TABLE_PREFIX: {{ .Values.wordpress.env.WORDPRESS_TABLE_PREFIX | quote }}
