apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}-wordpress
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.wordpress.replicaCount }}
  selector:
    matchLabels:
      {{- include "wordpress.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: wordpress
  template:
    metadata:
      labels:
        {{- include "wordpress.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: wordpress
    spec:
      containers:
        - name: wordpress
          image: "{{ .Values.wordpress.image.repository }}:{{ .Values.wordpress.image.tag }}"
          imagePullPolicy: {{ .Values.wordpress.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          envFrom:
            - configMapRef:
                name: {{ include "wordpress.fullname" . }}-wordpress
            - secretRef:
                name: {{ include "wordpress.fullname" . }}-mysql
          env:
            - name: WORDPRESS_DB_USER
              value: {{ .Values.mysql.auth.username | quote }}
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
          resources:
            {{- toYaml .Values.wordpress.resources | nindent 12 }}
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: {{ include "wordpress.fullname" . }}-wordpress
