apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress.fullname" . }}-wordpress
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.wordpress.persistence.accessMode }}
  storageClassName: {{ .Values.global.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.wordpress.persistence.size }}
