# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  # Client VM конфиг
  config.vm.define "bash" do |bash|
    bash.vm.box = "ubuntu/focal64"
    bash.vm.hostname = "bash"
    bash.vm.network "private_network", ip: "192.168.56.14"
    bash.vm.boot_timeout = 600
    
    bash.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get upgrade -y
    SHELL
  end
end