# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Создаем ssh ключ
  unless File.exist?("keys/vagrant_rsa")
    system("mkdir -p keys && ssh-keygen -t rsa -b 4096 -f keys/vagrant_rsa -N '' -q")
  end

  # Server VM конфиг
  config.vm.define "server" do |server|
    server.vm.box = "ubuntu/focal64"
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.56.10"
    server.vm.boot_timeout = 600    
    server.vm.provision "file", source: "keys/vagrant_rsa.pub", destination: "/home/vagrant/.ssh/authorized_keys"
    server.vm.provision "shell", path: "scripts/common.sh"
    server.vm.provision "shell", path: "scripts/server.sh"
  end

  # store VM конфиг
  config.vm.define "store" do |store|
    store.vm.box = "ubuntu/focal64"
    store.vm.hostname = "store"
    store.vm.network "private_network", ip: "192.168.56.11"
    store.vm.boot_timeout = 600    
    store.vm.provision "file", source: "keys/vagrant_rsa", destination: "/home/vagrant/.ssh/id_rsa"
    store.vm.provision "shell", path: "scripts/common.sh"
    store.vm.provision "shell", path: "scripts/store.sh"
  end
end