Vagrant.configure("2") do |config|
  config.vm.define "server" do |server|
    server.vm.box = "ubuntu/focal64"
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.56.10"
    server.vm.boot_timeout = 600 
    server.vm.provision "shell", path: "scripts/setup_mysql.sh"
    server.vm.provision "shell", path: "scripts/mysql_backup.sh"

  end

  config.vm.define "store" do |store|
    store.vm.box = "ubuntu/focal64"
    store.vm.hostname = "store"
    store.vm.network "private_network", ip: "192.168.56.20"
    store.vm.boot_timeout = 600 
    store.vm.provision "shell", path: "scripts/rsyncd.sh"
  end
end