Vagrant.configure("2") do |config|
  config.vm.define "server" do |server|
    server.vm.box = "ubuntu/focal64"
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.56.21"
    server.vm.boot_timeout = 600 
    server.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt install -y mysql-server
    sudo systemctl enable mysql
    sudo systemctl start mysql
    SHELL

  end

  config.vm.define "store" do |store|
    store.vm.box = "ubuntu/focal64"
    store.vm.hostname = "store"
    store.vm.network "private_network", ip: "192.168.56.31"
    store.vm.boot_timeout = 600
    store.vm.provision "shell", inline: <<-SHELL 
    sudo apt update
    sudo apt install -y rsync
    SHELL
  end
end